#+TODO:TODO(t@) WORKING(w!) IDEA(i@) | DONE(d@) REJECTED(r@)
#+TODO:REPORT(r@) BUG(b@) KNOWNCAUSE(k@) | FIXED(f@)
#+ARCHIVE: ::* Archived

* TODO Сделать вкладку со сделками
  - State "TODO"       from ""           [2011-03-11 Птн 12:45] \\
    вкладка с деревом сделок в котором отображаются все данные по сделкам
    введенным в базу. Вложенность в дереве сделок определяется уровнем
    расписанности сделки. Кнопка с хоткеем для быстрого ручного добавления
    сделок, в том числе парных. Возможность удаления сделок. Фильтр по
    дате, бумаге, количеству, цене, направлению сделки, а также по статусу
    сделки, возможность перехода к позиции, которой сделка принадлежит.

* TODO Сделать вкладке с позициями
  - State "TODO"       from ""           [2011-03-11 Птн 12:51] \\
    Вкладка с позициями. Возможность разбития отдельных позиций и всех
    сразу. Возможность ручного комбинирования сделок в позиции (скорее
    всего это во вкладке со сделками лучше сделать). Фильтр для сделок по
    бумаге, лось / профит, длинная / короткая, количество цена открытия
    цена закрытия, дата.
